// Mock data для карты мира
export const countriesData = {
  "US": { name: "США", code: "US" },
  "CA": { name: "Канада", code: "CA" },
  "MX": { name: "Мексика", code: "MX" },
  "BR": { name: "Бразилия", code: "BR" },
  "AR": { name: "Аргентина", code: "AR" },
  "GB": { name: "Великобритания", code: "GB" },
  "FR": { name: "Франция", code: "FR" },
  "DE": { name: "Германия", code: "DE" },
  "IT": { name: "Италия", code: "IT" },
  "ES": { name: "Испания", code: "ES" },
  "RU": { name: "Россия", code: "RU" },
  "CN": { name: "Китай", code: "CN" },
  "IN": { name: "Индия", code: "IN" },
  "JP": { name: "Япония", code: "JP" },
  "KR": { name: "Южная Корея", code: "KR" },
  "AU": { name: "Австралия", code: "AU" },
  "ZA": { name: "ЮАР", code: "ZA" },
  "EG": { name: "Египет", code: "EG" },
  "NG": { name: "Нигерия", code: "NG" },
  "KE": { name: "Кения", code: "KE" },
  "TR": { name: "Турция", code: "TR" },
  "SA": { name: "Саудовская Аравия", code: "SA" },
  "IR": { name: "Иран", code: "IR" },
  "IQ": { name: "Ирак", code: "IQ" },
  "AF": { name: "Афганистан", code: "AF" },
  "PK": { name: "Пакистан", code: "PK" },
  "BD": { name: "Бангладеш", code: "BD" },
  "TH": { name: "Таиланд", code: "TH" },
  "VN": { name: "Вьетнам", code: "VN" },
  "MY": { name: "Малайзия", code: "MY" },
  "ID": { name: "Индонезия", code: "ID" },
  "PH": { name: "Филиппины", code: "PH" },
  "NZ": { name: "Новая Зеландия", code: "NZ" },
  "NO": { name: "Норвегия", code: "NO" },
  "SE": { name: "Швеция", code: "SE" },
  "FI": { name: "Финляндия", code: "FI" },
  "DK": { name: "Дания", code: "DK" },
  "PL": { name: "Польша", code: "PL" },
  "UA": { name: "Украина", code: "UA" },
  "BY": { name: "Беларусь", code: "BY" },
  "KZ": { name: "Казахстан", code: "KZ" },
  "UZ": { name: "Узбекистан", code: "UZ" },
  "MN": { name: "Монголия", code: "MN" },
  "CL": { name: "Чили", code: "CL" },
  "PE": { name: "Перу", code: "PE" },
  "CO": { name: "Колумбия", code: "CO" },
  "VE": { name: "Венесуэла", code: "VE" },
  "EC": { name: "Эквадор", code: "EC" },
  "BO": { name: "Боливия", code: "BO" },
  "PY": { name: "Парагвай", code: "PY" },
  "UY": { name: "Уругвай", code: "UY" },
  "GF": { name: "Французская Гвиана", code: "GF" },
  "SR": { name: "Суринам", code: "SR" },
  "GY": { name: "Гайана", code: "GY" }
};

// Функция для получения данных страны по коду
export const getCountryData = (countryCode) => {
  return countriesData[countryCode] || { name: "Неизвестная страна", code: countryCode };
};