// Mock data для карты мира с расширенным списком стран
export const countriesData = {
  // Северная Америка
  "US": { name: "США", code: "US" },
  "CA": { name: "Канада", code: "CA" },
  "MX": { name: "Мексика", code: "MX" },
  "GT": { name: "Гватемала", code: "GT" },
  "BZ": { name: "Белиз", code: "BZ" },
  "SV": { name: "Сальвадор", code: "SV" },
  "HN": { name: "Гондурас", code: "HN" },
  "NI": { name: "Никарагуа", code: "NI" },
  "CR": { name: "Коста-Рика", code: "CR" },
  "PA": { name: "Панама", code: "PA" },
  
  // Южная Америка
  "BR": { name: "Бразилия", code: "BR" },
  "AR": { name: "Аргентина", code: "AR" },
  "CL": { name: "Чили", code: "CL" },
  "PE": { name: "Перу", code: "PE" },
  "CO": { name: "Колумбия", code: "CO" },
  "VE": { name: "Венесуэла", code: "VE" },
  "EC": { name: "Эквадор", code: "EC" },
  "BO": { name: "Боливия", code: "BO" },
  "PY": { name: "Парагвай", code: "PY" },
  "UY": { name: "Уругвай", code: "UY" },
  "GF": { name: "Французская Гвиана", code: "GF" },
  "SR": { name: "Суринам", code: "SR" },
  "GY": { name: "Гайана", code: "GY" },
  
  // Европа
  "GB": { name: "Великобритания", code: "GB" },
  "FR": { name: "Франция", code: "FR" },
  "DE": { name: "Германия", code: "DE" },
  "IT": { name: "Италия", code: "IT" },
  "ES": { name: "Испания", code: "ES" },
  "PT": { name: "Португалия", code: "PT" },
  "NL": { name: "Нидерланды", code: "NL" },
  "BE": { name: "Бельгия", code: "BE" },
  "CH": { name: "Швейцария", code: "CH" },
  "AT": { name: "Австрия", code: "AT" },
  "NO": { name: "Норвегия", code: "NO" },
  "SE": { name: "Швеция", code: "SE" },
  "FI": { name: "Финляндия", code: "FI" },
  "DK": { name: "Дания", code: "DK" },
  "IS": { name: "Исландия", code: "IS" },
  "IE": { name: "Ирландия", code: "IE" },
  "PL": { name: "Польша", code: "PL" },
  "CZ": { name: "Чехия", code: "CZ" },
  "SK": { name: "Словакия", code: "SK" },
  "HU": { name: "Венгрия", code: "HU" },
  "RO": { name: "Румыния", code: "RO" },
  "BG": { name: "Болгария", code: "BG" },
  "GR": { name: "Греция", code: "GR" },
  "HR": { name: "Хорватия", code: "HR" },
  "SI": { name: "Словения", code: "SI" },
  "BA": { name: "Босния и Герцеговина", code: "BA" },
  "RS": { name: "Сербия", code: "RS" },
  "ME": { name: "Черногория", code: "ME" },
  "MK": { name: "Северная Македония", code: "MK" },
  "AL": { name: "Албания", code: "AL" },
  "EE": { name: "Эстония", code: "EE" },
  "LV": { name: "Латвия", code: "LV" },
  "LT": { name: "Литва", code: "LT" },
  "UA": { name: "Украина", code: "UA" },
  "BY": { name: "Беларусь", code: "BY" },
  "MD": { name: "Молдова", code: "MD" },
  
  // Россия и СНГ
  "RU": { name: "Россия", code: "RU" },
  "KZ": { name: "Казахстан", code: "KZ" },
  "UZ": { name: "Узбекистан", code: "UZ" },
  "TM": { name: "Туркменистан", code: "TM" },
  "TJ": { name: "Таджикистан", code: "TJ" },
  "KG": { name: "Киргизия", code: "KG" },
  "AZ": { name: "Азербайджан", code: "AZ" },
  "AM": { name: "Армения", code: "AM" },
  "GE": { name: "Грузия", code: "GE" },
  
  // Азия
  "CN": { name: "Китай", code: "CN" },
  "IN": { name: "Индия", code: "IN" },
  "JP": { name: "Япония", code: "JP" },
  "KR": { name: "Южная Корея", code: "KR" },
  "KP": { name: "Северная Корея", code: "KP" },
  "MN": { name: "Монголия", code: "MN" },
  "TH": { name: "Таиланд", code: "TH" },
  "VN": { name: "Вьетнам", code: "VN" },
  "MY": { name: "Малайзия", code: "MY" },
  "SG": { name: "Сингапур", code: "SG" },
  "ID": { name: "Индонезия", code: "ID" },
  "PH": { name: "Филиппины", code: "PH" },
  "BN": { name: "Бруней", code: "BN" },
  "LA": { name: "Лаос", code: "LA" },
  "KH": { name: "Камбоджа", code: "KH" },
  "MM": { name: "Мьянма", code: "MM" },
  "BD": { name: "Бангладеш", code: "BD" },
  "BT": { name: "Бутан", code: "BT" },
  "NP": { name: "Непал", code: "NP" },
  "LK": { name: "Шри-Ланка", code: "LK" },
  "MV": { name: "Мальдивы", code: "MV" },
  "AF": { name: "Афганистан", code: "AF" },
  "PK": { name: "Пакистан", code: "PK" },
  "IR": { name: "Иран", code: "IR" },
  "IQ": { name: "Ирак", code: "IQ" },
  "SY": { name: "Сирия", code: "SY" },
  "TR": { name: "Турция", code: "TR" },
  "IL": { name: "Израиль", code: "IL" },
  "PS": { name: "Палестина", code: "PS" },
  "JO": { name: "Иордания", code: "JO" },
  "LB": { name: "Ливан", code: "LB" },
  "SA": { name: "Саудовская Аравия", code: "SA" },
  "YE": { name: "Йемен", code: "YE" },
  "OM": { name: "Оман", code: "OM" },
  "AE": { name: "ОАЭ", code: "AE" },
  "QA": { name: "Катар", code: "QA" },
  "BH": { name: "Бахрейн", code: "BH" },
  "KW": { name: "Кувейт", code: "KW" },
  "CY": { name: "Кипр", code: "CY" },
  
  // Африка
  "EG": { name: "Египет", code: "EG" },
  "LY": { name: "Ливия", code: "LY" },
  "TN": { name: "Тунис", code: "TN" },
  "DZ": { name: "Алжир", code: "DZ" },
  "MA": { name: "Марокко", code: "MA" },
  "SD": { name: "Судан", code: "SD" },
  "SS": { name: "Южный Судан", code: "SS" },
  "ET": { name: "Эфиопия", code: "ET" },
  "ER": { name: "Эритрея", code: "ER" },
  "DJ": { name: "Джибути", code: "DJ" },
  "SO": { name: "Сомали", code: "SO" },
  "KE": { name: "Кения", code: "KE" },
  "UG": { name: "Уганда", code: "UG" },
  "TZ": { name: "Танзания", code: "TZ" },
  "RW": { name: "Руанда", code: "RW" },
  "BI": { name: "Бурundi", code: "BI" },
  "MG": { name: "Мадагаскар", code: "MG" },
  "MU": { name: "Маврикий", code: "MU" },
  "ZA": { name: "ЮАР", code: "ZA" },
  "ZW": { name: "Зимбабве", code: "ZW" },
  "BW": { name: "Ботсвана", code: "BW" },
  "NA": { name: "Намибия", code: "NA" },
  "ZM": { name: "Замбия", code: "ZM" },
  "MW": { name: "Малави", code: "MW" },
  "MZ": { name: "Мозамбик", code: "MZ" },
  "AO": { name: "Ангола", code: "AO" },
  "CD": { name: "ДР Конго", code: "CD" },
  "CG": { name: "Республика Конго", code: "CG" },
  "CF": { name: "ЦАР", code: "CF" },
  "CM": { name: "Камерун", code: "CM" },
  "TD": { name: "Чад", code: "TD" },
  "NE": { name: "Нигер", code: "NE" },
  "NG": { name: "Нигерия", code: "NG" },
  "BJ": { name: "Бенин", code: "BJ" },
  "TG": { name: "Того", code: "TG" },
  "GH": { name: "Гана", code: "GH" },
  "CI": { name: "Кот-д'Ивуар", code: "CI" },
  "LR": { name: "Либерия", code: "LR" },
  "SL": { name: "Сьерра-Леоне", code: "SL" },
  "GN": { name: "Гвинея", code: "GN" },
  "GW": { name: "Гвинея-Бисау", code: "GW" },
  "SN": { name: "Сенегал", code: "SN" },
  "GM": { name: "Гамбия", code: "GM" },
  "ML": { name: "Мали", code: "ML" },
  "BF": { name: "Буркина-Фасо", code: "BF" },
  "MR": { name: "Мавритания", code: "MR" },
  
  // Океания
  "AU": { name: "Австралия", code: "AU" },
  "NZ": { name: "Новая Зеландия", code: "NZ" },
  "PG": { name: "Папуа — Новая Гвинея", code: "PG" },
  "FJ": { name: "Фиджи", code: "FJ" },
  "SB": { name: "Соломоновы Острова", code: "SB" },
  "VU": { name: "Вануату", code: "VU" },
  "NC": { name: "Новая Каледония", code: "NC" },
  "WS": { name: "Самоа", code: "WS" },
  "TO": { name: "Тонга", code: "TO" },
  "KI": { name: "Кирибати", code: "KI" },
  "TV": { name: "Тувалу", code: "TV" },
  "NR": { name: "Науру", code: "NR" },
  "PW": { name: "Палау", code: "PW" },
  "FM": { name: "Микронезия", code: "FM" },
  "MH": { name: "Маршалловы Острова", code: "MH" }
};

// Функция для получения данных страны по коду
export const getCountryData = (countryCode) => {
  return countriesData[countryCode] || { name: "Неизвестная страна", code: countryCode };
};